server:
  port: ${PORT:8084}

spring:
  application:
    name: reporting-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:1234567890123456789012345678901234567890}
    internal-api-key: ${APP_SECURITY_INTERNAL_API_KEY:inventory-internal-key}
  clients:
    catalog:
      base-url: ${APP_CLIENTS_CATALOG_BASE_URL:}
    inventory:
      base-url: ${APP_CLIENTS_INVENTORY_BASE_URL:}
